#!/bin/sh

# store $@ into argv
argv=$@


gg_p() {
	# populate
	# for each file in $argv, except the first two
	for file in ${argv[@]:2}
	do
		idcontent="$(git log -n 1 --pretty=format:%H -- "$file" | tr -d '\n' && git ls-files --full-name -s "$file" | tr -d '\n')"

		sed -e "s|\\$\Git.*\\$|\\$\Git: $idcontent \\$|g" -i '' "$file"
	done
}

gg_s() {
	# strip
	# for each file in $argv, except the first two
	for file in ${argv[@]:2}
	do
		sed -e "s|\\$\Git.*\\$|\\$\Git\\$|g" -i '' "$file"
	done
}

# parse args
case $1 in
	-p)
		gg_p
		;;
	-s)
		gg_s
		;;
	*)
		echo "Usage: gitgoat [-p|-s] [file1] [file2] ..."
		;;
esac

# end of file